{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "bc73b778",
   "metadata": {
    "_cell_guid": "b1076dfc-b9ad-4769-8c92-a6c4dae69d19",
    "_uuid": "8f2839f25d086af736a60e9eeb907d3b93b6e0e5",
    "papermill": {
     "duration": 0.003187,
     "end_time": "2022-12-10T00:53:33.524179",
     "exception": false,
     "start_time": "2022-12-10T00:53:33.520992",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "88405ef8",
   "metadata": {
    "papermill": {
     "duration": 0.001937,
     "end_time": "2022-12-10T00:53:33.528178",
     "exception": false,
     "start_time": "2022-12-10T00:53:33.526241",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "---\n",
    "title: 'Case study: Cyclistic'\n",
    "author: \"Mariia Shilovskaia\"\n",
    "date: \"2022-11-18\"\n",
    "output: pdf_document\n",
    "---\n",
    "\n",
    "# Introduction\n",
    "\n",
    "This is a case study for my Google Data Analytics certificate course. In this case study I analyze a public data set about a bike-share company in Chicago. This document describes six steps of the data analysis process: ask, prepare, process, analyze, share, and act.\n",
    "\n",
    "## Scenario\n",
    "\n",
    "A junior data analyst working in the marketing analyst team at Cyclistic, a bike-share company in Chicago. The director of marketing believes the company’s future success depends on maximizing the number of annual memberships. Therefore, a team wants to understand how casual riders and annual members use Cyclistic bikes differently. From these insights, the team will design a new marketing strategy to convert casual riders into annual members. But first, Cyclistic executives must approve recommendations, so they must be backed up with compelling data insights and professional data visualizations.\n",
    "\n",
    "## Step 1: Ask\n",
    "\n",
    "Three questions will guide the future marketing program:\n",
    "\n",
    "* How do annual members and casual riders use Cyclistic bikes differently?\n",
    "* Why would casual riders buy Cyclistic annual memberships?\n",
    "* How can Cyclistic use digital media to influence casual riders to become members?\n",
    "\n",
    "The director of marketing and your manager has assigned the first question to answer: How do annual members and casual riders use Cyclistic bikes differently?\n",
    "\n",
    "### Key tasks\n",
    "\n",
    "Identify the business task. Analyze the 12 months of Cyclistic customer data, find the difference between annual members and casual riders and compose marketing program for converting casual riders to annual members.\n",
    "\n",
    "Consider key stakeholders. Director of Marketing, marketing analytics team, executive team.\n",
    "\n",
    "Deliverable: A list of differences between the casual riders and annual members.\n",
    "\n",
    "## Step 2: Prepare\n",
    "\n",
    "Cyclistic’s historical trip data for 2021 was used to analyze and identify trends and explore how different customer types are using Cyclistic bikes. The data was made available by Motivate International Inc. under this [license](https://ride.divvybikes.com/data-license-agreement). \n",
    "\n",
    "### Key tasks\n",
    "\n",
    "Download data and store it appropriately. The Data has been downloaded and have been stored on my computer. The data is located in public dataset divvy-tripdata [link](https://divvy-tripdata.s3.amazonaws.com/index.html).\n",
    "\n",
    "Identify how it’s organized. The data stored in CSV files, and there are a total of 13 columns in each files. The data is provided by a third-party called Motivate International Inc.\n",
    "\n",
    "Sort and filter the data. 12 months of data from 2021 was used for this analysis. The data has a large sample size, more than million rows in total.\n",
    "\n",
    "Determine the credibility of the data. Data-privacy issues prohibit me from using riders’ personally identifiable information and I can't determine if riders have purchased multiple single passes.\n",
    "\n",
    "Deliverable: A description of all data sources used.\n",
    "\n",
    "## Step 3: Process\n",
    "\n",
    "### Key tasks\n",
    "\n",
    "Check the data for errors. Сheck for duplicates, inconsistencies. \n",
    "\n",
    "Choose your tools. Use the R programming language because the data set has more than a million rows in total.\n",
    "\n",
    "Transform the data to work with it effectively. Merge all 12 csv files into one. \n",
    "\n",
    "Document the cleaning process. Create a document for all steps of the process.\n",
    "\n",
    "Deliverable: Documentation of any cleaning or manipulation of data.\n",
    "\n",
    "### Install and load necessary packages in R\n",
    "\n",
    "Install and load necessary packages in R\n",
    "\n",
    "```\n",
    "install.packages(\"tidyverse\")\n",
    "install.packages(\"lubridate\")\n",
    "install.packages(\"ggplot2\")\n",
    "install.packages(\"dplyr\")\n",
    "install.packages(\"readr\")\n",
    "install.packages(\"magrittr\")\n",
    "install.packages(\"geosphere\")\n",
    "\n",
    "library(tidyverse)\n",
    "library(lubridate)\n",
    "library(ggplot2)\n",
    "library(dplyr)\n",
    "library(readr)\n",
    "library(magrittr)\n",
    "library(geosphere)\n",
    "getwd() # Displays your working directory\n",
    "setwd(\"/Users/...) # Sets your working directory to simplify calls to data\n",
    "```\n",
    "#### Import data to R studio:\n",
    "\n",
    "```\n",
    "m01_2021 <- read_csv(\"Divvy_Trips_2021_01.csv\")\n",
    "m02_2021 <- read_csv(\"Divvy_Trips_2021_02.csv\")\n",
    "m03_2021 <- read_csv(\"Divvy_Trips_2021_03.csv\")\n",
    "m04_2021 <- read_csv(\"Divvy_Trips_2021_04.csv\")\n",
    "m05_2021 <- read_csv(\"Divvy_Trips_2021_05.csv\")\n",
    "m06_2021 <- read_csv(\"Divvy_Trips_2021_06.csv\")\n",
    "m07_2021 <- read_csv(\"Divvy_Trips_2021_07.csv\")\n",
    "m08_2021 <- read_csv(\"Divvy_Trips_2021_08.csv\")\n",
    "m09_2021 <- read_csv(\"Divvy_Trips_2021_09.csv\")\n",
    "m10_2021 <- read_csv(\"Divvy_Trips_2021_10.csv\")\n",
    "m11_2021 <- read_csv(\"Divvy_Trips_2021_11.csv\")\n",
    "m12_2021 <- read_csv(\"Divvy_Trips_2021_12.csv\")\n",
    "```\n",
    "\n",
    "#### Compare all column names of each of the files. \n",
    "\n",
    "If column names is different, rename column name  to make them consistent:\n",
    "```\n",
    "colnames(m01_2021)\n",
    "colnames(m02_2021)\n",
    "colnames(m03_2021)\n",
    "colnames(m04_2021)\n",
    "colnames(m05_2021)\n",
    "colnames(m06_2021)\n",
    "colnames(m07_2021)\n",
    "colnames(m08_2021)\n",
    "colnames(m09_2021)\n",
    "colnames(m10_2021)\n",
    "colnames(m11_2021)\n",
    "colnames(m12_2021)\n",
    "```\n",
    "#### Check that all the data sets have the same number of columns, same type of columns and names:\n",
    "```\n",
    "str(m01_2021)\n",
    "str(m02_2021)\n",
    "str(m03_2021)\n",
    "str(m04_2021)\n",
    "str(m05_2021)\n",
    "str(m06_2021)\n",
    "str(m07_2021)\n",
    "str(m08_2021)\n",
    "str(m09_2021)\n",
    "str(m10_2021)\n",
    "str(m11_2021)\n",
    "str(m12_2021)\n",
    "```\n",
    "#### Merge all files in one and inspect for inconsistencies:\n",
    "```\n",
    "all_trips_2021 <- bind_rows(m01_2021,m02_2021,m03_2021,m04_2021,m05_2021,m06_2021,m07_2021,m08_2021,m09_2021,m10_2021,m11_2021,m12_2021)\n",
    "```\n",
    "#### Statistical summary of data:\n",
    "```\n",
    "str(all_trips_2021) # List of columns and data types\n",
    "colnames(all_trips_2021) # List of column names\n",
    "dim(all_trips_2021) # Dimensions of the data frame\n",
    "head(all_trips_2021) # The first 6 rows of the data frame\n",
    "tail(all_trips_2021) # The last 6 rows of the data frame\n",
    "summary(all_trips_2021) # Statistical summary of data\n",
    "all_trips_2021 %>% distinct() # Remove duplicate rows in the data frame\n",
    "```\n",
    "#### Add columns for date, month, year, day of the week into the data frame:\n",
    "```\n",
    "all_trips_2021$date <- as.Date(all_trips_2021$started_at)\n",
    "all_trips_2021$month <- format(as.Date(all_trips_2021$date), \"%m\")\n",
    "all_trips_2021$day <- format(as.Date(all_trips_2021$date), \"%d\")\n",
    "all_trips_2021$year <- format(as.Date(all_trips_2021$date), \"%Y\")\n",
    "all_trips_2021$day_of_week <- format(as.Date(all_trips_2021$date), \"%A\")\n",
    "\n",
    "colnames(all_trips_2021) # Check the names of all the columns in the data frame\n",
    "```\n",
    "#### Add a new columns:  \n",
    "\n",
    "Add a \"ride_length\" calculation to the data frame:\n",
    "```\n",
    "all_trips_2021$ride_length <- difftime(all_trips_2021$ended_at,all_trips_2021$started_at)\n",
    "str(all_trips_2021) #Check the structure of the columns\n",
    "is.factor(all_trips_2021$ride_length) # Check if the object passed to the function is a Factor or not\n",
    "all_trips_2021$ride_length <- as.numeric(as.character(all_trips_2021$ride_length)) # Convert \"ride_length\" from Factor to numeric\n",
    "is.numeric(all_trips_2021$ride_length) # Check if the values are regarded as numeric\n",
    "```\n",
    "\n",
    "The data frame includes a few hundred entries when bikes were taken out of docks and checked for quality by Divvy. Otherwise a ride length is negative or \"0\":\n",
    "\n",
    "```\n",
    "all_trips_2021_v2 <- all_trips_2021[!(all_trips_2021$ride_length <= 0),]\n",
    "```\n",
    "\n",
    "Add ride_distance calculation in km to the data frame:\n",
    "```\n",
    "all_trips_2021_v2$ride_distance <- distGeo(matrix(c(all_trips_2021_v2$start_lng, all_trips_2021_v2$start_lat), ncol=2), matrix (c(all_trips_2021_v2$end_lng, all_trips_2021_v2$end_lat), ncol=2))\n",
    "all_trips_2021_v2$ride_distance <- all_trips_2021_v2$ride_distance/1000 # Set ride_distance in km\n",
    "```\n",
    "\n",
    "## Step 4: Analysis\n",
    "\n",
    "### Key tasks\n",
    "\n",
    "Aggregate the data so it’s useful and accessible.\n",
    "\n",
    "Organize and format the data.\n",
    "\n",
    "Perform calculations.\n",
    "\n",
    "Identify trends and relationships.\n",
    "\n",
    "Deliverable: A summary of data analysis.\n",
    "\n",
    "### Conduct descriptive analysis:\n",
    "\n",
    "#### Descriptive analysis on column 'ride_length':\n",
    "\n",
    "```\n",
    "mean(all_trips_2021_v2$ride_length) # The straight average (total ride length / rides)\n",
    "median(all_trips_2021_v2$ride_length) # The midpoint number in the ascending array of ride lengths\n",
    "max(all_trips_2021_v2$ride_length) # The longest ride\n",
    "min(all_trips_2021_v2$ride_length) # The shortest ride\n",
    "```\n",
    "\n",
    "#### Compare members and casual users:\n",
    "```\n",
    "aggregate(all_trips_2021_v2$ride_length ~ all_trips_2021_v2$member_casual, FUN = mean)\n",
    "aggregate(all_trips_2021_v2$ride_length ~ all_trips_2021_v2$member_casual, FUN = median)\n",
    "aggregate(all_trips_2021_v2$ride_length ~ all_trips_2021_v2$member_casual, FUN = max)\n",
    "aggregate(all_trips_2021_v2$ride_length ~ all_trips_2021_v2$member_casual, FUN = min)\n",
    "aggregate(all_trips_2021_v2$ride_length ~ all_trips_2021_v2$member_casual + all_trips_2021_v2$day_of_week, FUN = mean) # The average ride time by each day for members vs casual users\n",
    "\n",
    "all_trips_2021_v2$day_of_week <- ordered(all_trips_2021_v2$day_of_week, levels=c(\"Sunday\", \"Monday\", \"Tuesday\", \"Wednesday\", \"Thursday\", \"Friday\", \"Saturday\")) # Set the order for the column 'day_of_week'\n",
    "\n",
    "aggregate(all_trips_2021_v2$ride_length ~ all_trips_2021_v2$member_casual + all_trips_2021_v2$day_of_week, FUN = mean) # The right order of the column 'day_of_week'\n",
    "```\n",
    "\n",
    "#### Analyze ridership data by type and weekday:\n",
    "```\n",
    "all_trips_2021_v2 %>% \n",
    "    mutate(weekday = wday(started_at, label = TRUE)) %>% # Creates weekday field using wday()\n",
    "    group_by(member_casual, weekday) %>% # G roups by usertype and weekday\n",
    "    summarise(number_of_rides = n() #The number of rides and average duration\n",
    "    ,average_duration = mean(ride_length))  %>% # The average duration\n",
    "    arrange(member_casual, weekday) #Sort\n",
    "\n",
    "all_trips_2021_v2 %>% \n",
    "    mutate(weekday = wday(started_at, label = TRUE)) %>% \n",
    "    group_by(member_casual, weekday) %>% \n",
    "    summarise(number_of_rides = n()     \n",
    "    ,average_ride_length = mean(ride_length),.groups=\"drop\") %>%\n",
    "    arrange(member_casual, weekday)\n",
    "```\n",
    "## Step 5: Share\n",
    "\n",
    "### Key tasks\n",
    "\n",
    "Determine the best way to share your findings. Share findings in the presentation. \n",
    "\n",
    "Create effective data visualizations. Compose plots in R Studio. \n",
    "\n",
    "Present findings. Prepared the presentation with all findings.\n",
    "\n",
    "Ensure the result is accessible. Check visualization for accessibility. \n",
    "\n",
    "Deliverable: Supporting visualizations and key findings.\n",
    "\n",
    "### Key findings summary:\n",
    "\n",
    "* Members of Cyclistic use bikes more on weekdays.\n",
    "* Casual riders are more active on the weekends.\n",
    "* Casual riders rent for longer periods of time than members.\n",
    "* June to September is the most popular season to rent a bike.\n",
    "* A ride distance increases on weekends for both groups.\n",
    "\n",
    "### Visualizing the number of rides by rider type:\n",
    "```\n",
    "#plot_1\n",
    "all_trips_2021_v2 %>% \n",
    "    mutate(weekday = wday(started_at, label = TRUE)) %>% \n",
    "    group_by(member_casual, weekday) %>% \n",
    "    summarise(number_of_rides = n()\n",
    "              ,average_duration = mean(ride_length)) %>% \n",
    "    arrange(member_casual, weekday)  %>% \n",
    "    ggplot(aes(x = weekday, y = number_of_rides, fill = member_casual)) +\n",
    "    geom_col(position = \"dodge\")+\n",
    "    labs(title=\"Total rides by Members and Casual riders vs. Day of the week \")\n",
    "```\n",
    "\n",
    "```\n",
    "#plot_2\n",
    "all_trips_2021_v2 %>% \n",
    "    mutate(weekday = wday(started_at, label = TRUE)) %>% \n",
    "    group_by(member_casual, weekday) %>% \n",
    "    summarise(number_of_rides = n()\n",
    "              ,average_duration = mean(ride_length)) %>% \n",
    "    arrange(member_casual, weekday)  %>% \n",
    "    ggplot(aes(x = weekday, y = average_duration, fill = member_casual)) +\n",
    "    geom_col(position = \"dodge\")+\n",
    "    labs(title=\"Average duration of Members and Casual riders vs. Day of the week\")\n",
    "```\n",
    "\n",
    "```\n",
    "#plot_3\n",
    "all_trips_2021_v2 %>% \n",
    "    mutate(weekday = wday(started_at, label = TRUE)) %>% \n",
    "    group_by(member_casual, weekday) %>% drop_na() %>%\n",
    "    summarise(average_ride_distance = mean(ride_distance)) %>% \n",
    "    ggplot(aes(x = weekday, y = average_ride_distance, fill = member_casual)) +\n",
    "    geom_col(position = \"dodge\")+\n",
    "    labs(title=\"Average ride distance by Members and Casual riders vs. Day of the week \")\n",
    "```\n",
    "\n",
    "```\n",
    "#plot_4\n",
    "all_trips_2021_v2 %>%  \n",
    "  group_by(member_casual, month) %>% \n",
    "  summarise(number_of_rides = n(),.groups=\"drop\") %>% \n",
    "  arrange(member_casual, month)  %>% \n",
    "  ggplot(aes(x = month, y = number_of_rides, fill = member_casual)) +\n",
    "  labs(title =\"Total rides by Members and Casual riders by Month\") +\n",
    "  geom_col(width=0.5, position = position_dodge(width=0.5)) +\n",
    "  scale_y_continuous(labels = function(x) format(x, scientific = FALSE))\n",
    "```\n",
    "\n",
    "```\n",
    "#plot_5\n",
    "all_trips_2021_v2 %>%   \n",
    "    group_by(member_casual, day_of_week) %>% \n",
    "    summarise(number_of_rides = n(), .groups=\"drop\") %>% \n",
    "    arrange(member_casual, day_of_week) %>% \n",
    "    ggplot(aes(x = day_of_week, y = number_of_rides, fill = member_casual)) +\n",
    "    labs(title =\"Total rides of Members and Casual riders Vs. Day of the week\") +\n",
    "    geom_col(width=1, position = position_dodge(width=1))\n",
    "```\n",
    "\n",
    "```\n",
    "#plot_6\n",
    "all_trips_2021_v2 %>%  \n",
    "  group_by(member_casual, rideable_type) %>% \n",
    "  summarise(average_ride_length = mean(ride_length), .groups=\"drop\") %>%\n",
    "  ggplot(aes(x = rideable_type, y = average_ride_length, fill = member_casual)) +\n",
    "  geom_col(width=1, position = position_dodge(width=1)) + \n",
    "  labs(title =\"Average ride time of Members and Casual riders vs. Type of the bike\")\n",
    "```\n",
    "\n",
    "```\n",
    "#plot_7\n",
    "all_trips_2021_v2 %>% \n",
    "    group_by(member_casual, rideable_type) %>% \n",
    "    summarise(number_of_rides = n()\n",
    "              ,average_duration = mean(ride_length)) %>% \n",
    "    arrange(rideable_type) %>% \n",
    "    ggplot(aes(x = rideable_type, y = number_of_rides, fill = member_casual)) +\n",
    "    geom_col(position = \"dodge\")+\n",
    "    labs(title=\"Total rides by the type of the bike\")\n",
    "```\n",
    "\n",
    "## Step 6: Act\n",
    "Prepare the presentation with the top three recommendations based on the analysis.\n",
    "\n",
    "### Key tasks\n",
    "\n",
    "Solve the problem.\n",
    "\n",
    "Apply insights.\n",
    "\n",
    "Make a data-driven decision.\n",
    "\n",
    "Deliverable: The top three recommendations based on your analysis.\n",
    "\n",
    "### Recommendations:\n",
    "\n",
    "* Add seasonal rates with privileges for member riders.\n",
    "* Provide discounts on weekends with membership.\n",
    "* Prepare a loyalty program to encourage members to ride on weekends and longer distances.\n",
    "* Continue to collect data including demographics for future analysis.\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6500f30a",
   "metadata": {
    "papermill": {
     "duration": 0.00182,
     "end_time": "2022-12-10T00:53:33.531812",
     "exception": false,
     "start_time": "2022-12-10T00:53:33.529992",
     "status": "completed"
    },
    "tags": []
   },
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "R",
   "language": "R",
   "name": "ir"
  },
  "language_info": {
   "codemirror_mode": "r",
   "file_extension": ".r",
   "mimetype": "text/x-r-source",
   "name": "R",
   "pygments_lexer": "r",
   "version": "4.0.5"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 4.429405,
   "end_time": "2022-12-10T00:53:33.655416",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2022-12-10T00:53:29.226011",
   "version": "2.4.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
